CREATE USER 'java'@'localhost' IDENTIFIED BY 'java123';

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'java'@'localhost' WITH GRANT OPTION;

CREATE DATABASE java;

DROP TABLE students;

USE java;

CREATE TABLE students (
    id int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name varchar(255) NOT NULL ,
    age int(3) NOT NULL,
    city varchar(255) NOT NULL,
    created TIMESTAMP default CURRENT_TIMESTAMP
);

DROP TABLE absen;

CREATE TABLE absen (
    id int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    keterangan varchar(255) NOT NULL ,
    date TIMESTAMP default CURRENT_TIMESTAMP,
    student_id int,
    FOREIGN KEY (student_id) REFERENCES students(id)
);

INSERT INTO absen (keterangan, student_id) VALUES
('hadir', 1),('hadir', 1),
('hadir', 2),('izin', 2),
('hadir', 3),('hadir', 3),
('hadir', 4),('izin', 4),
('hadir', 5),('hadir', 5),
('hadir', 6),('alpha', 6),
('hadir', 7),('hadir', 7),
('hadir', 8),('izin', 8),
('hadir', 9),('hadir', 9),
('alpha', 10),('alpha', 10);


INSERT INTO students (name, age, city) VALUES
('Romy Saputra Sihananda', 17, 'Blitar'),
('Laraine Hinako Terralyn', 17, 'Macon'),
('Giles Juna Jad', 31, 'Brighton'),
('Carlon Davey Jamaar', 43, 'Fairfield'),
('Galdino Mariesha Praneeth', 30, 'Austin'),
('Jaydn Feng Mace', 40, 'Utica'),
('Kloey Tayna Lisa', 46, 'Alexandria'),
('Aydan Christina Jayci', 46, 'Omaha'),
('Cliff Anapaula Jazlynn', 16, 'San Buenaventura'),
('Donye Jarah Kaevon', 15, 'Columbus'),
('Ellice Mariane Abbigal', 38, 'Havre de Grace'),
('Jaquann Dresean Khiry', 24, 'Frederick'),
('Jorell Cortez Asija', 42, 'Cedar Rapids'),
('Alasia Amunet Ryan', 47, 'Apple Valley'),
('Devina Jill Nabila', 42, 'Muskegon'),
('Nichele Berish Jahmir', 26, 'Santa Rosa'),
('Maryn Jermell Jailon', 47, 'Clarke County'),
('Darryle Luisdavid Emaline', 26, 'Columbia'),
('Dusten Jeison Arlana', 43, 'Muskegon'),
('Kayde Damieon Majed', 32, 'Modesto'),
('Kortnee Brittni Ajane', 16, 'Arlington'),
('Rashi Daylan Swati', 16, 'Washington'),
('Alecxis Cid Amy', 17, 'Yakima'),
('Kendalle Sherell Angelita', 48, 'Racine'),
('Bianca Lorretta Stryker', 37, 'Oxnard'),
('Yamileth Bethanee Jorell', 20, 'Cincinnati'),
('Delvin Maryalice Melchizedek', 39, 'Port Arthur'),
('Winona Mykenna Briahnna', 36, 'Albuquerque'),
('Damiana Rafia Darrien', 42, 'Kalamazoo'),
('Anhthu Jamina Jaheem', 20, 'Fremont'),
('Koa Shyanna Yanelli', 50, 'Paterson'),
('Giovani Sachit Arionna', 34, 'Jackson'),
('Devron Hassam Indira', 37, 'Las Vegas'),
('Lorrie Dillen Latavia', 37, 'Hampton'),
('Andi Justina Dalena', 21, 'Eugene'),
('Bhavna Del Jane', 16, 'Brighton'),
('Dallyn Karrigan Braydee', 34, 'Thousand Oaks'),
('Aymee Lorenz Tate', 38, 'Kissimmee'),
('Khoi Mattison Delyla', 32, 'Salem'),
('Daison Linnaea Brookelynn', 38, 'Clearwater'),
('Marisah Ahmari Xavianna', 18, 'Simi Valley'),
('Sadiq Eoin Esvin', 27, 'Greensboro'),
('Decameron Kraig Aeriana', 45, 'Sarasota'),
('Jaxson Greyson Christy', 22, 'Huntsville'),
('Quashon Silva Mariya', 34, 'Lorain'),
('Marcial Faithlynn Terra', 33, 'Tucson'),
('Adrienne Adiel Orrin', 45, 'Appleton'),
('Brydon Odin Krystian', 38, 'Grand Rapids'),
('Caitland Marlena Jamia', 38, 'Medford'),
('Aneisa Melvina Cristel', 26, 'Lubbock'),
('Amilee Darion Matao', 22, 'Newburgh'),
('Deantae Eusebio Jamin', 35, 'Hagerstown'),
('Reymond Anup Jacobus', 32, 'Westminster'),
('Lennie Brody Wynonna', 48, 'Oceanside'),
('Bryam Charlotta Yanira', 38, 'Hollywood'),
('Alwin Tmya Hasmik', 40, 'Springdale'),
('Saturnino Jazline Damar', 45, 'Cedar Rapids'),
('Genessis Ivyanna Deseray', 22, 'Baton Rouge'),
('Stav Dyson Kalvin', 36, 'North Charleston'),
('Tashae Camiryn Shreya', 43, 'Roseville'),
('Gillian Perl Daphine', 50, 'Asheville'),
('Laresha Joey Keilee', 39, 'McAllen'),
('Skye Rito Carlyann', 21, 'Mission Viejo'),
('Rainna Deontrae Victorria', 25, 'Sunnyvale'),
('Leara Deyona Timira', 50, 'Murfreesboro'),
('Aleece Anta Jerrica', 49, 'Antioch'),
('Xylia Kegan Jehiel', 40, 'Portsmouth'),
('Nhat Alithea Denys', 48, 'Lacey'),
('Deann Trevaun Norberto', 17, 'Syracuse'),
('Shavar Malisha Shakinah', 22, 'Layton'),
('Marayah Levina Rehan', 32, 'Dallas'),
('Tyshelle Sanaz Naveen', 37, 'Greensboro'),
('Saba Niyla Allysen', 37, 'Tuscaloosa'),
('Brietta Marianna Blerta', 30, 'Palm Bay'),
('Brene Quiera Shallah', 39, 'Racine'),
('Devony Collen Amaranta', 41, 'South Bend'),
('Labrandon Scot Kieanna', 49, 'Fort Walton Beach'),
('Kaisee Derrian Adrea', 46, 'Round Lake Beach'),
('Leoncio Serafina Damontae', 41, 'Frederick'),
('Ailaina Keelon Jalana', 21, 'New York City'),
('Kelis Roseanne Tehya', 32, 'Fontana'),
('Tyquell Cullen Winni', 35, 'Clearwater'),
('Azhia Ajanique Biana', 15, 'Newark'),
('Jeron Maxwell Donnae', 41, 'Lowell'),
('Margret Sachit Alaza', 18, 'San Antonio'),
('Abdulai Sharah Angelis', 35, 'Laredo'),
('Gretchen Ramya Mayce', 47, 'Norwich'),
('Jeneva Rondale Kynadee', 35, 'Berkeley'),
('Joan Drelyn Meya', 41, 'Kennewick'),
('Giovan Ajanique Albany', 25, 'Cleveland'),
('Shayn Maxie Effie', 39, 'Riverside'),
('Janaye Sameer Elin', 49, 'Lacey'),
('Midajah Shoshanna Chanston', 19, 'San Francisco'),
('Aerion Demetreus Sharnell', 22, 'Poughkeepsie'),
('Fredy Katura Micaleb', 36, 'Laredo'),
('Scot Damisha Kateryn', 16, 'Gainesville'),
('Dishawn Nayaly Blade', 35, 'Madison'),
('Imara Georgio Shemiah', 48, 'Richland'),
('Charizma Alton Abdulah', 32, 'Oakland'),
('Katilyn Keiondre Grey', 49, 'Toledo'),
('Joy Mindy Keierra', 35, 'Elkhart'),
('Elieser Jarret Tymeshia', 29, 'Carrollton'),
('Luna Devarious Naiyah', 15, 'Amarillo'),
('Keng Christipher Javon', 25, 'Pueblo'),
('Eisha Arella Tiauna', 26, 'Charlotte'),
('Teauna Colm Sophee', 30, 'Orem'),
('Rourke Manny Mauri', 18, 'Myrtle Beach'),
('Elicio Nassim Juliah', 40, 'Peoria'),
('Kami Nissim Rickie', 19, 'York'),
('Treshon Rusty Adelia', 41, 'Santa Clara'),
('Matigan Grabiela Chantal', 48, 'Indianapolis'),
('Darius Moussa Keyonia', 39, 'Racine'),
('Ruddy Lyle Kazuya', 22, 'Rancho Cucamonga'),
('Shawndell Marycatherine Ronte', 22, 'New York'),
('Libbi Bruna Bailea', 42, 'Melbourne'),
('Arline Viviana Trayton', 41, 'South Bend'),
('Harland Jadah Alliana', 28, 'Colorado Springs'),
('Soila Kayla Taelor', 39, 'Boulder'),
('Khamaron Prarthana Rubi', 35, 'Hayward'),
('Santonio Aza Timeshia', 23, 'Frederick'),
('Levelle Kadon Rucha', 24, 'Havre de Grace'),
('Daqwan Caysey Meryl', 28, 'Atlantic City'),
('Tomar Rito Sabrina', 45, 'Kaneohe'),
('Maanas Carman Jenaro', 27, 'Sioux Falls'),
('Jenasia Stephani Schuyler', 36, 'Abilene'),
('Lamel Derique Rounak', 15, 'Downey'),
('Brieann Harmony Aliece', 16, 'Albuquerque'),
('Susanne Prabhjot Carlena', 32, 'Odessa'),
('Sharissa Indiana Terena', 34, 'Fort Worth'),
('Jaime Paden Darriona', 17, 'Melbourne'),
('Eero Erique Zyaria', 41, 'Atlantic City'),
('Manjot Serita Magaly', 22, 'Indianapolis'),
('Hyrum Lynsi Calina', 15, 'Philadelphia'),
('Brenen Deion Quade', 48, 'Montgomery'),
('Malyssa Teri Jessi', 29, 'McHenry'),
('Romy Kaylaann Nou', 30, 'Pompano Beach'),
('Annais Shalayah Cassandra', 44, 'Palm Springs'),
('Kamiya Ahava Dre', 24, 'Lubbock'),
('Duquan Cornel Rease', 37, 'North Charleston'),
('Davonna Jaden Alivia', 19, 'Hickory'),
('Rory Daje Tyran', 21, 'Ocala'),
('Lynzey Elisebeth Genia', 16, 'Fullerton'),
('Jd Isak Ethan', 42, 'Anchorage'),
('Stefanos Anastashia Monea', 23, 'Omaha'),
('Denyce Kandyce Shaniya', 35, 'Elizabeth'),
('Aishani Khiry Esthefany', 34, 'St. Paul'),
('Reynold Aston Parris', 44, 'Salt Lake City'),
('Nikhita Keylan Yesmin', 16, 'Pasadena'),
('Kaitlen Jerelyn Anael', 26, 'Vallejo'),
('Chely Jashonna Lochlan', 49, 'Sarasota'),
('Annabel Karrington Mychael', 24, 'Virginia Beach'),
('Aunya Lucianna Soomin', 47, 'Arlington'),
('Thanya Anallely Anise', 37, 'Utica'),
('Alden Annah Jashay', 35, 'Punta Gorda'),
('Tylar Caelan Korrin', 35, 'Arvada'),
('Keven Montanna Roshaun', 40, 'Santa Clara'),
('Camren Jyquez Chaela', 20, 'Richmond County'),
('Demisha Brookelynn Ewan', 19, 'Jefferson'),
('Alishia Tahlor Faustino', 15, 'Providence'),
('Akshita Ashlan Mattelyn', 15, 'San Buenaventura'),
('Shanise Ahmad Prisila', 48, 'Yonkers'),
('Zamariah Azelia Keelyn', 28, 'Saint Petersburg'),
('Tinamarie Marnesha Devun', 50, 'Muskegon'),
('Tila Skylynn Alura', 22, 'Santa Barbara'),
('Truly Tatayana Lionel', 24, 'Pueblo'),
('Dquan Dreshon Nahomi', 25, 'Murfreesboro'),
('Tej Talea Kiele', 44, 'Sioux City'),
('Letisia Izak Jayon', 39, 'Philadelphia'),
('Hendrik Jayvian Breshawn', 36, 'Reading'),
('Nazair Jakhi Amritha', 41, 'Panama City'),
('Alacia Stephon Louann', 21, 'Paterson'),
('Cintia Madasyn Braeden', 34, 'Anchorage'),
('Teran Jamell Khylee', 20, 'Rochester'),
('Auston Britini Sonni', 20, 'Columbus'),
('Ewelina Yewande Chukwuemeka', 50, 'College Station'),
('Tyjae Andraya Michaelanthony', 34, 'Dayton'),
('Keyante Janicia Cherokee', 31, 'Portsmouth'),
('Mahiya Panagiotis Braelin', 26, 'Harrisburg'),
('Abbygale Tona Oswin', 43, 'Durham'),
('Myasia Feliz Chrystina', 45, 'Huntington'),
('Ronie Diego Hasana', 25, 'Lakeland'),
('Myrka Latavion Geovanna', 47, 'Panama City'),
('Addison Penny Torionna', 41, 'Saint Paul'),
('Breiana Savona Aphrodite', 23, 'New Haven'),
('Abrina Danessa Shalin', 42, 'Orlando'),
('Rayaan Lovell Edgard', 42, 'Huntington'),
('Sheina Jessup Amyia', 46, 'New York'),
('Sarit Manley Dshawn', 21, 'Boston'),
('Delonta Angelly Tylesha', 31, 'Carrollton'),
('Treanthony Daichi Arlicia', 20, 'Harrisburg'),
('Rio Corion Talik', 27, 'Denver'),
('Yun Angalina Paizlee', 48, 'Ogden'),
('Emmarie Mamadou Uziel', 42, 'Rancho Cucamonga'),
('Lochlyn Talis Taima', 25, 'Pomona'),
('Azucena Deera Eustolia', 23, 'Raleigh'),
('Nazeer Marygrace Jeovanni', 16, 'Buffalo'),
('Chistopher Whitlee Shanterria', 40, 'Howell'),
('Akhilesh Bennie Layla', 49, 'Raleigh'),
('Everette Domenique Ammar', 27, 'Davenport'),
('Illyanna Tahara Mallorie', 41, 'Jersey City'),
('Tereso Monserratt Jessy', 37, 'Naples'),
('Cecille Shenika Tashia', 28, 'Canton'),
('Stevie Judd Laniya', 40, 'New London'),
('Khori Jadarian Karis', 23, 'Melbourne'),
('Tonna Marsha Jackson', 38, 'Tampa'),
('Lylah Malloree Saphire', 19, 'Las Vegas'),
('Jayelin Logan Daytona', 43, 'Irving'),
('Jared Natallie Kyon', 38, 'North Port'),
('Hadlie Kalob Amiyah', 48, 'Independence'),
('Shiori Kili Antonio', 44, 'Birmingham'),
('Christianjames Yaa Janiaya', 48, 'Tampa'),
('Marcous Kalijah Anagha', 34, 'Plano'),
('Kimber Fawwaz Arisbeth', 17, 'Baltimore'),
('Maham Matigan Quentavious', 49, 'Lakewood'),
('Ming Aisa Rayven', 42, 'Fremont'),
('Javani Tameka Adrie', 28, 'Independence'),
('Lilia Montavius Rahshawn', 24, 'Lewisville'),
('Amerah Froilan Rini', 47, 'Miami'),
('Makalla Bret Miyana', 35, 'Daytona Beach'),
('Alysson Mylia Eddie', 24, 'Garden Grove'),
('Whitley Lamiya Malorie', 31, 'Lakewood'),
('Aija Sumin Kaylen', 44, 'Saint Petersburg'),
('Allora Devena Kiegan', 28, 'Palmdale'),
('Azha Pierra Jamonte', 32, 'Wichita'),
('Roshaun Jahron Sequan', 26, 'Pomona'),
('Ashanti Tegan Noeli', 48, 'Elkhart'),
('Demarques Trevor Chas', 16, 'McAllen'),
('Romeo Makel Nathanael', 45, 'Joliet'),
('Rayyan Hezekiah Jesiah', 19, 'Seaside'),
('Dymin Mabel Danixa', 45, 'Houma'),
('Ilisa Josua Elibeth', 18, 'Evansville'),
('Holden Jayln Neila', 27, 'Bethlehem'),
('Lynzie Daysi Tashae', 36, 'Normal'),
('Daion Elasia Crystin', 44, 'Houston'),
('Abril Damya Awan', 28, 'Medford'),
('Shakyah Monte Raheim', 29, 'Flint'),
('Daegan Alyssha Yesly', 31, 'Kenosha'),
('Mahdi Kannon Kalleigh', 33, 'Victorville'),
('Tahmid Manning Lynnett', 47, 'New York'),
('Lysa Alfonso Kierrah', 15, 'Bonita Springs'),
('Chanah Soomin Kyanne', 41, 'Winston'),
('Geronimo Kailena Maiah', 27, 'Redding'),
('Ladarien Jalene Kwasi', 29, 'Akron'),
('Lyric Jahmya Millennium', 48, 'Topeka'),
('Milad Nassim Quintavius', 43, 'Anchorage'),
('Nikoleta Anmol Gianelle', 25, 'Flint'),
('Jalessa Prestin Ky', 44, 'Muskegon'),
('Abi Jakelyne Reeve', 26, 'Gulfport-Biloxi'),
('Callaghan Robynne Kerrigan', 49, 'Long Beach'),
('Antrell Javiera Elliana', 21, 'Fresno'),
('Gray Santasia Yazlin', 43, 'Paterson'),
('Falicia Maleki Kenry', 46, 'New Orleans'),
('Paxton Eulalio Tycen', 28, 'Tempe'),
('Ranique Nashea Chantia', 22, 'Huntsville'),
('Mariyah Jayah Mirlinda', 16, 'Vallejo'),
('Navy Shealeigh Lawrence', 44, 'Tulsa'),
('Sakshi Alessandro Miquez', 48, 'El Paso'),
('Asyria Talor Kristopher', 49, 'Lincoln'),
('Viktor Travaris Delila', 48, 'Lorain'),
('Marryn Keiandre Natisha', 22, 'Pasadena'),
('Leyla Argelia Davier', 27, 'Fort Smith'),
('Kennethia Akirah Mable', 25, 'Richland'),
('Chriselle Yan Johnnathan', 26, 'Amarillo'),
('Syona Jackelynn Quade', 23, 'Simi Valley'),
('Javiel Mehek Koda', 39, 'Hartford'),
('Eirene Adaja Caitlyn', 30, 'Albuquerque'),
('Scarlette Locke Emelyn', 36, 'San Jose'),
('Daphny Aunya Kiandre', 38, 'Anaheim'),
('Thea Jakaya Yates', 40, 'Baton Rouge'),
('Madelyn Elver Kindle', 39, 'Albany'),
('Timera Jadira Rubie', 39, 'Athens'),
('Kaitlyn Mackenze Maciel', 43, 'Gastonia'),
('Keisy Lynnsey Chapin', 42, 'Columbus'),
('Taleya Damichael Niki', 18, 'Marina'),
('Xavia Deven Brailey', 29, 'Port Saint Lucie'),
('Dejon Parish Jaliel', 31, 'Stockton'),
('Shohei Stevenson Phillis', 20, 'Colorado Springs'),
('Aleema Kayshaun Karla', 31, 'Syracuse'),
('Tymeek Nathen Mackinzee', 16, 'Scottsdale'),
('Aakilah Jailyn Zackary', 47, 'Toledo'),
('Destyni Reyes Ladajia', 43, 'Kailua'),
('Ena Srikar Karyme', 38, 'Mission Viejo'),
('Philippe Makinsey Delecia', 32, 'Cathedral City'),
('Maddi Zulema Jannessa', 26, 'Spokane'),
('Cimone Jennelle Elspeth', 43, 'Murfreesboro'),
('Johnhenry Drucilla Britanee', 47, 'Fullerton'),
('Mallory Ngozi Israel', 20, 'Carrollton'),
('Nathanael Payam Justise', 35, 'Brighton'),
('Brelynn Anajah Corbin', 36, 'Raleigh'),
('Tamon Randi Lenna', 16, 'Sarasota'),
('Yaremi Ephriam Kelynn', 37, 'San Antonio'),
('Felisity Melaney Nashae', 34, 'Aurora'),
('Kasidi Tavien Braleigh', 19, 'St. Paul'),
('Avelino Sareena Marius', 23, 'West Covina'),
('Urbano Katianna Warrick', 42, 'Wichita'),
('Uchechi Madisson Micael', 18, 'Grand Rapids'),
('Princeton Nori Marnie', 37, 'York'),
('Meridyth Kalob Reeanna', 28, 'Lake Charles'),
('Lyndsi Annise Tareq', 26, 'Omaha'),
('Terell Tayla Nikia', 34, 'Hollywood'),
('Zeynep Nygil Bryahna', 26, 'Knoxville'),
('Tamarick Cristal Caelyn', 48, 'Allentown'),
('Solene Peony Koi', 42, 'Greenville'),
('Cornesha Dayon Drelyn', 18, 'Apple Valley'),
('Timyia Mickayla Jacki', 50, 'Buffalo'),
('Tashana Shay Jahnari', 42, 'Stockton'),
('Monee Danett Enyah', 46, 'New London'),
('Milly Nnaemeka Sira', 42, 'Port Orange'),
('Jacqui Oved Storie', 35, 'Bel Air'),
('Bliss Shaunna Montae', 30, 'Cedar Rapids'),
('Falisha Maxwel Gilbert', 31, 'San Buenaventura'),
('Jeaneth Daniele Katelin', 40, 'Madison'),
('Kenan Paulina Collan', 23, 'Santa Clara'),
('Kaydee Kalila Leara', 27, 'Kansas City'),
('Klara Briesha Suhaib', 29, 'Wilmington'),
('Jadiss Jaselle Kyel', 35, 'Saint Petersburg'),
('Gerson Lari Tayva', 45, 'Simi Valley'),
('Laisa Jerusalem Sheron', 18, 'Cambridge'),
('Jayna Kendell Breiana', 18, 'Davidson County'),
('Diana Kielah Emmalee', 41, 'Reading'),
('Malin Jacqeline Destani', 44, 'Baton Rouge'),
('Kollyn Nohely Mystie', 22, 'Scottsdale'),
('Alexiea Cortlynn Joangel', 35, 'Atlanta'),
('Renae Alecea Ragan', 15, 'Fitchburg'),
('Katerina Solana Rashawn', 33, 'Saint Louis'),
('Annabel Blayze Khali', 39, 'Santa Barbara'),
('Nataja Laycie Hrithik', 31, 'Corona'),
('Jhovany Timberly Kehinde', 40, 'Spartanburg'),
('Luisantonio Dartanyon Santos', 36, 'Cedar Rapids'),
('Brindy Trevyn Neosha', 28, 'West Valley City'),
('Tandre Martavius Najat', 34, 'Rochester'),
('Amiaya Swati Shenise', 47, 'Cape Coral'),
('Jared Jaicie Tykeya', 34, 'Lowell'),
('Tyshia Khamar Denali', 31, 'New York City'),
('Deyja Sherlyn Jadelin', 40, 'Trenton'),
('Mariah Terriana Samual', 43, 'Beaumont'),
('Mariane Tamisha Jayme', 47, 'Minneapolis'),
('Makinzy Marcela Danny', 43, 'San Bernardino'),
('Jerrid Yvonna Tameron', 48, 'Green Bay'),
('Anitra Zhane Mystique', 26, 'Burbank'),
('Ori Aylyn Starrlynn', 41, 'El Monte'),
('Edis Jaidon Catrin', 47, 'Wichita'),
('Antavion Jesua Kamira', 36, 'Pueblo'),
('Rosmeri Starlena Jibran', 23, 'Knoxville'),
('Pressley Cabe Terric', 37, 'Waterloo'),
('Leina Eleanora Alex', 44, 'Greensboro'),
('Angellena Darryn Kiara', 33, 'Santa Barbara'),
('Keaundra Servando Dontrae', 45, 'Richland'),
('Jamin Cheyne Zaneta', 50, 'Saginaw'),
('Hajar Tristyn Jetta', 45, 'Saint Paul'),
('Ahlyssa Elisavet Aleesa', 18, 'Sarasota'),
('Sherae Yesly Lizeth', 18, 'Salinas'),
('Traveion Gabreil Blue', 49, 'Little Rock'),
('Florencio Estiven Earl', 15, 'New London'),
('Katalena Quincey Horatio', 31, 'Rochester'),
('Anahis Dorrien Rees', 28, 'Stamford'),
('Infinity Sharmin Juwuan', 39, 'Youngstown'),
('Aladdin Abriel Iris', 29, 'Waterloo'),
('Winnie Amisa Erich', 44, 'Gulfport-Biloxi'),
('Tiernan Kyra Fatime', 28, 'Gulfport-Biloxi'),
('Ruthanna Kendallyn Elijaha', 46, 'Portsmouth'),
('Meylin Deanglo Sedrick', 35, 'Hialeah'),
('Adiel Aris Doroteo', 40, 'Buffalo'),
('Kaushal Reyn Jarad', 50, 'El Monte'),
('Matilda Laycie Queenie', 41, 'Waco'),
('Hasin Veronique Abijah', 45, 'Stockton'),
('Aleighsha Daytona Saraina', 35, 'Minneapolis'),
('Alianna Arionne Harley', 28, 'Brighton'),
('Marvel Emili Sierria', 40, 'Athens'),
('Tristyn Tijana Tera', 26, 'Myrtle Beach'),
('Stafford Kiamara Kaylynne', 26, 'Hemet'),
('Darnesha Milik Starlee', 22, 'Austin'),
('Genaya Eulalia Jacqualyn', 15, 'Lakewood'),
('Tiphany Leona Jemima', 47, 'Downey'),
('Nelsy Devina Haeleigh', 18, 'Huntsville'),
('Sarahann Abiel Doua', 24, 'Youngstown'),
('Antanique Natallia Anyae', 15, 'Richmond'),
('Emary Micaya Jimena', 43, 'New York'),
('Lucca Nyela Rosalie', 43, 'Roseville'),
('Keyleigh Angad Jordanne', 49, 'Sebastian'),
('Marcelle Aila Emeri', 35, 'Nashville'),
('Starsha Elliot Ramzy', 35, 'Bellevue'),
('Prarthana Kindra Carlynn', 36, 'Tempe'),
('Thatcher Abrar Jeanne', 34, 'Norwalk'),
('Elliette Marialuisa Dimetri', 32, 'Lexington'),
('Braeden Calib Greta', 37, 'Sarasota'),
('Tryniti Stanton Zarian', 47, 'Lafayette'),
('Linton Meyer Amarylis', 24, 'Paterson'),
('Aliese Aneliz Shakaira', 22, 'Elk Grove'),
('Amani Jaasiel Rubin', 39, 'Kenosha'),
('Rodman Joby Ian', 37, 'Paterson'),
('Zierra Maile Saskia', 35, 'Coral Springs'),
('Kaitlyne Brock Remigio', 36, 'Sioux Falls'),
('Karriem Beyonce Beyonca', 26, 'Montgomery'),
('Veyda Caeli Brok', 18, 'Cary'),
('Hunter Zayanna Arun', 50, 'Eugene'),
('Kyland Arion Krystle', 17, 'San Bernardino'),
('Shakiyah Ana Collen', 15, 'New York'),
('Vanessa Sarrah Nicolle', 26, 'Richmond County'),
('Anijah Katyana Erion', 42, 'Fort Worth'),
('Chante Karriem Imer', 41, 'Honolulu'),
('Savonna Alysa Nolberto', 43, 'Clarke County'),
('Lizzeth Bryar Israa', 28, 'Portland'),
('Lizzy Keely Danasia', 22, 'Lowell'),
('Finlay Vida Tayton', 37, 'Kennewick'),
('Ellery Kaitelyn Lilliann', 24, 'Duluth'),
('Elisa Lahari Elaiza', 36, 'Poughkeepsie'),
('Ashad Princess Dejanae', 30, 'Overland Park'),
('Janssen Aquil Tracen', 47, 'Visalia'),
('Makendra Marlon Hennessy', 15, 'Carrollton'),
('Gracianna Aesha Merilyn', 36, 'South Bend'),
('Valente Dierre Bodee', 26, 'Temecula'),
('Byanka Aleiyah Freja', 34, 'Modesto'),
('Keayla Madai Shakota', 29, 'Orlando'),
('Sheamus Isadore Jerid', 34, 'Richland'),
('Ibrahim Anibal Lean', 25, 'Beaumont'),
('Aryonna Johnjoseph Lakota', 28, 'Pensacola'),
('Shaunae Ki Reo', 33, 'Hagerstown'),
('Nadine Keeyan Tytionna', 23, 'Bethlehem'),
('Della Jeniffer Christoffer', 44, 'Odessa'),
('Tahir Daysie Nedim', 17, 'Lafayette'),
('Deidre Jabria Saraann', 48, 'San Diego'),
('Iqbal Erika Shianna', 32, 'Green Bay'),
('Tanis Jahne Robie', 38, 'Rochester'),
('Skylee Braxston Hafsah', 24, 'Arlington'),
('Shervin Kalen Sunny', 49, 'Chandler'),
('Darrian Tabia Caitlen', 28, 'Miami'),
('Kimiko Saheed Cindy', 35, 'Burbank'),
('Tere Artisha Rhylee', 34, 'Lincoln'),
('Apurva Merisa Rehema', 47, 'Hialeah'),
('Kolbi Cira Takenya', 29, 'Manchester'),
('Yendi Kirkland Ingri', 15, 'Round Lake Beach'),
('Elwyn Laurelyn Meegan', 42, 'Las Cruces'),
('Lashaye Jahmaal Werner', 27, 'Montgomery'),
('Madlynn Marymichael Jerren', 41, 'Detroit'),
('Kwan Leron Jasia', 38, 'Anaheim'),
('Jamonica Kyser Kyce', 28, 'Vallejo'),
('Cutler Torri Shella', 16, 'Minneapolis'),
('Gianni Addeline Lucas', 19, 'Berkeley'),
('Majesti Edwin Jinan', 16, 'Bel Air'),
('Mariela Arrington Tracey', 32, 'Madison'),
('Kayana Monce Araia', 49, 'Spartanburg'),
('Briseyda Oniel Jaleigha', 40, 'Odessa'),
('Jamaul Kassidy Shiyanne', 33, 'Pasadena'),
('Francesco Horlando Ash', 49, 'Hialeah'),
('Rasha Amel Natan', 16, 'Boston'),
('Chasmine Leopoldo Mileydi', 19, 'Costa Mesa'),
('Nicholai Lydell Dinora', 28, 'Harlingen'),
('Kalijah Raequan Mychala', 37, 'Modesto'),
('Savanha Kavona Leland', 23, 'Glendale'),
('Kayliana Danette Jene', 40, 'Palm Bay'),
('Corben Karo Rhiannon', 25, 'Portland'),
('Brita Kenzy Onya', 21, 'Clearwater'),
('Zaira Allanna Deshawn', 42, 'Sacramento'),
('Keiondre Moria Micale', 48, 'Orange'),
('Josuha Adenike Arrianna', 20, 'Savannah'),
('Yesnia Tashai Jamel', 17, 'Saginaw'),
('Marion Dontre Clover', 44, 'San Francisco'),
('Gabryella Pawel Tyasia', 24, 'Santa Barbara'),
('Cheryl Lourdes Jasin', 47, 'Pittsburgh'),
('Jakwan Margaux Kyrin', 31, 'Utica'),
('Aukai Kadesha Ophelia', 40, 'High Point'),
('Remi Destene Jamaury', 22, 'Myrtle Beach'),
('Carly Malini Brigit', 31, 'San Bernardino'),
('Keenan Maycie Aldair', 48, 'Havre de Grace'),
('Harper Ridge Nora', 30, 'Paterson'),
('Gwendolynn Shahad Jatavis', 25, 'Overland Park'),
('Jakaila Anysia Dajhon', 50, 'Boulder'),
('Ania Shalice Damondre', 30, 'Mesa'),
('Rubith Surya Kassidy', 29, 'Paterson'),
('Chrystina Manika Corinne', 24, 'Ann Arbor'),
('Tal Daejah Triston', 26, 'Port Arthur'),
('Kerah Precilla Johannes', 41, 'Chula Vista'),
('Melanye Braylen Zavery', 23, 'Roseville'),
('Abiel Corryn Savina', 42, 'Washington'),
('Brittnay Renea Maleea', 39, 'Lansing'),
('Blaine Tysheem Fintan', 31, 'Cape Coral'),
('Tremel Isamar Lirim', 18, 'Austin'),
('Braden Tywanda Lindsey', 22, 'Mesquite'),
('Tarren Najilah Burak', 37, 'Normal'),
('Job Marieli Nellie', 39, 'Lafayette'),
('Jaiden Ryliegh Shawne', 24, 'Scottsdale'),
('Walther Pavel Megha', 15, 'Leominster'),
('Maciej Terrelle Francis', 28, 'New London'),
('Jamesmatthew Jaythan Ashanna', 31, 'Lorain'),
('Mayson Mahoganie Shella', 38, 'Washington'),
('Jadus Jeniya Alysia', 22, 'Athens'),
('Cassondra Jaycee Alania', 25, 'Danbury'),
('Angelus Leo Sabiha', 32, 'Worcester'),
('Thunder Asahel Niam', 16, 'Tallahassee'),
('Jaquaveon Polo Rockwell', 19, 'Normal'),
('Burt Aliceson Andraea', 27, 'Tulsa'),
('Errol Maisie Iyah', 24, 'North Las Vegas'),
('Nyah Darianne Reannah', 23, 'Hemet'),
('Hugo Jerremy Travious', 16, 'Bonita Springs'),
('Laterra Jamie Scottie', 50, 'New Orleans'),
('Jacquelene Aleksi Flynn', 25, 'Seattle'),
('Detric Kimiya Senna', 33, 'Utica'),
('Rayvon Urvi Marques', 27, 'Scranton'),
('Jameslee Malinda Adelin', 21, 'San Jose'),
('Kileigh Langston Sharona', 47, 'Pensacola'),
('Genoveva Jersey Aneesa', 48, 'Raleigh'),
('Gianella Quinterria Madesyn', 33, 'Santa Rosa'),
('Taggart Aaronisha Camillemarie', 47, 'Daly City'),
('Areon Kunal Delany', 23, 'Corpus Christi'),
('Rolan Kyshaun Kaytlynn', 23, 'Monroe'),
('Chase Myrian Marcea', 31, 'Carrollton');